CREATE TABLE payments (
  id BINARY(16) NOT NULL PRIMARY KEY,
  order_id BINARY(16) NOT NULL,
  provider VARCHAR(24) NOT NULL,
  provider_order_id VARCHAR(64) NOT NULL,
  provider_payment_id VARCHAR(64) NULL,
  provider_status VARCHAR(32) NULL,
  amount BIGINT NOT NULL,
  currency CHAR(3) NOT NULL,
  status VARCHAR(24) NOT NULL,
  method VARCHAR(24) NULL,
  failure_code VARCHAR(64) NULL,
  failure_reason VARCHAR(255) NULL,
  authorized_at DATETIME(6) NULL,
  captured_at DATETIME(6) NULL,
  refunded_amount BIGINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT uq_provider_order UNIQUE (provider, provider_order_id),
  CONSTRAINT uq_provider_payment UNIQUE (provider, provider_payment_id),
  CONSTRAINT ck_refunded CHECK (refunded_amount >= 0 AND refunded_amount <= amount),
  INDEX idx_payments_order (order_id),
  INDEX idx_payments_status_created (status, created_at)
);