package com.example.payment.exception;

public enum ErrorCode {
    VALIDATION_FAILED(400), UNAUTHORIZED(401), FORBIDDEN(403), NOT_FOUND(404),
    PRODUCT_NOT_PURCHASABLE(409), PRICE_NOT_FOUND(409),
    COUPON_INVALID(422), COUPON_EXHAUSTED(422),
    ORDER_ALREADY_PAID(409), ORDER_EXPIRED(409), INVALID_STATE_TRANSITION(409),
    IDEMPOTENCY_KEY_REQUIRED(400), IDEMPOTENCY_CONFLICT(422), IDEMPOTENCY_IN_PROGRESS(409),
    REFUND_EXCEEDS_REFUNDABLE(422), PAYMENT_NOT_REFUNDABLE(409),
    WEBHOOK_SIGNATURE_INVALID(400), PROVIDER_UNAVAILABLE(503), PROVIDER_ERROR(502),
    UPSTREAM_UNAVAILABLE(503), INTERNAL_ERROR(500);
    public final int http; ErrorCode(int h) { http = h; }
}