server:
  servlet:
    context-path: /tests-api

spring:
  application:
    name: test-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${TEST_SERVICE_DATABASE:test_db}?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}
    baseline-version: 18

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  cache:
    redis:
      enable-statistics: true

internal:
  auth:
    my-secret: ${TEST_SERVICE_SECRET}
    allowed-clients:
      api-gateway: ${API_GATEWAY_SERVICE_SECRET}
      attempt-service: ${ATTEMPT_SERVICE_SECRET}
      payment-service: ${PAYMENT_SERVICE_SECRET}

  services:
    community-url: ${COMMUNITY_SERVICE_URL}
    test-url: ${TEST_SERVICE_URL}
    attempt-url: ${ATTEMPT_SERVICE_URL}
    payment-url: ${PAYMENT_SERVICE_URL}
    
logging:
  level:
    com.example.testservice: INFO
    org.springframework.web: INFO

app:
  api:
    version: ${API_VERSION}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    cache:
      instrument: true